name: Test

on:
  push:

jobs:
  npm7-docker:
    name: NPM 7 install in Docker on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM install
        run: docker run --rm -it -v $PWD:/app -w /app node:${{ matrix.node }}-alpine /bin/sh -c "npm i -g npm@7 && npm i --legacy-peer-deps --verbose"
  npm7-local:
    name: NPM 7 install local on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM 7
        run: npm i -g npm@7
      - name: NPM install
        run: npm i --legacy-peer-deps --verbose
  npm6-docker:
    name: NPM 6 install in Docker on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM install
        run: docker run --rm -it -v $PWD:/app -w /app node:${{ matrix.node }}-alpine /bin/sh -c "npm i -g npm@6 && npm i --verbose"
  npm6-local:
    name: NPM 6 install local on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM 6
        run: npm i -g npm@6
      - name: NPM install
        run: npm i --verbose